version: "3"
services:
  hiber-presence:
    build:
      context: .
      args:
        NODE_ENV: "development"
    volumes:
      - .:/app:ro
      - /app/node_modules
    env_file:
      - ./.env.dev
    command: npm run dev
